name: HealthChecks EventStore CI

on:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.EventStore/**
      - test/HealthChecks.EventStore.Tests/**
      - .github/workflows/healthchecks_eventstore_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*

  pull_request:
    branches: [ master ]
    paths:
    - src/HealthChecks.EventStore/**
    - test/HealthChecks.EventStore.Tests/**
    - .github/workflows/healthchecks_eventstore_ci.yml
    - Directory.Build.props
    - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      eventstore:
        image: eventstore/eventstore
        ports:
          - "2113:2113"
          - "1113:1113"
        env:
          EVENTSTORE_INSECURE: true
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore
      run: |
        dotnet restore ./src/HealthChecks.EventStore/HealthChecks.EventStore.csproj &&
        dotnet restore ./test/HealthChecks.EventStore.Tests/HealthChecks.EventStore.Tests.csproj
    - name: Check formatting
      working-directory: ./src/HealthChecks.EventStore
      run: |
        dotnet format --no-restore --verify-no-changes --severity warn ./src/HealthChecks.EventStore/HealthChecks.EventStore.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1) &&
        dotnet format --no-restore --verify-no-changes --severity warn ./test/HealthChecks.EventStore.Tests/HealthChecks.EventStore.Tests.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1)
    - name: Build
      run: |
        dotnet build --no-restore ./src/HealthChecks.EventStore/HealthChecks.EventStore.csproj &&
        dotnet build --no-restore ./test/HealthChecks.EventStore.Tests/HealthChecks.EventStore.Tests.csproj
    - name: Test
      run: dotnet test --no-restore --no-build ./test/HealthChecks.EventStore.Tests/HealthChecks.EventStore.Tests.csproj
