name: HealthChecks Redis CI

on:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.Redis/**
      - test/HealthChecks.Redis.Tests/**
      - .github/workflows/healthchecks_redis_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
  pull_request:
    branches: [ master ]
    paths:
    - src/HealthChecks.Redis/**
    - test/HealthChecks.Redis.Tests/**
    - .github/workflows/healthchecks_redis_ci.yml
    - Directory.Build.props
    - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.102
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.Redis/HealthChecks.Redis.csproj
    - name: Check formatting
      working-directory: ./src/HealthChecks.Redis
      run: |
        dotnet format --no-restore --verify-no-changes --severity warn || (echo "Run 'dotnet format' to fix issues" && exit 1)
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.Redis/HealthChecks.Redis.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.Redis.Tests/HealthChecks.Redis.Tests.csproj
