name: HealthChecks Consul CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.Consul/**
      - test/HealthChecks.Consul.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_consul_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.Consul/**
      - test/HealthChecks.Consul.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_consul_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    services:
      consul:
        image: hashicorp/consul:latest
        ports:
          - 8500:8500
          - 8600:8600

    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/HealthChecks.Consul/HealthChecks.Consul.csproj
      TEST_PROJECT_PATH: ./test/HealthChecks.Consul.Tests/HealthChecks.Consul.Tests.csproj
      CODECOV_FLAGS: Consul
