name: HealthChecks RavenDb CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.RavenDB/**
      - test/HealthChecks.RavenDb.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_ravendb_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.RavenDB/**
      - test/HealthChecks.RavenDb.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_ravendb_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    services:
      ravendb:
        image: ravendb/ravendb
        ports:
          - 9030:8080
        env:
          RAVEN_ARGS: --Setup.Mode=None

    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/HealthChecks.RavenDB/HealthChecks.RavenDB.csproj
      TEST_PROJECT_PATH: ./test/HealthChecks.RavenDb.Tests/HealthChecks.RavenDb.Tests.csproj
      CODECOV_FLAGS: RavenDb
