name: HealthChecks Elastic Search CI

on:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.Elasticsearch/**
      - test/HealthChecks.Elasticsearch.Tests/**
      - .github/workflows/healthchecks_elasticsearch_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
  pull_request:
    branches: [ master ]
    paths:
    - src/HealthChecks.Elasticsearch/**
    - test/HealthChecks.Elasticsearch.Tests/**
    - .github/workflows/healthchecks_elasticsearch_ci.yml
    - Directory.Build.props
    - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        ports:
          - 9300:9300
          - 9200:9200
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.Elasticsearch/HealthChecks.Elasticsearch.csproj
    - name: Check formatting
      working-directory: ./src/HealthChecks.Elasticsearch
      run: |
        dotnet format --no-restore --verify-no-changes --severity warn || (echo "Run 'dotnet format' to fix issues" && exit 1)
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.Elasticsearch/HealthChecks.Elasticsearch.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.Elasticsearch.Tests/HealthChecks.Elasticsearch.Tests.csproj --verbosity normal
