name: HealthChecks Publisher.CloudWatch CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.Publisher.CloudWatch/**
      - test/HealthChecks.Publisher.CloudWatch.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_publisher_cloudwatch_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.Publisher.CloudWatch/**
      - test/HealthChecks.Publisher.CloudWatch.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_publisher_cloudwatch_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      AWS_REGION: us-east-1
      PROJECT_PATH: ./src/HealthChecks.Publisher.CloudWatch/HealthChecks.Publisher.CloudWatch.csproj
      TEST_PROJECT_PATH: ./test/HealthChecks.Publisher.CloudWatch.Tests/HealthChecks.Publisher.CloudWatch.Tests.csproj
      CODECOV_FLAGS: Publisher.CloudWatch
