name: HealthChecks AzureServiceBus DB CI

on:
  workflow_dispatch:
  push:
   branches: [ master ]
   paths:
     - src/HealthChecks.Azure.Messaging.ServiceBus/**
     - test/HealthChecks.Azure.Messaging.ServiceBus.Tests/**
     - test/_SHARED/**
     - .github/workflows/healthchecks_azureservicebus_ci.yml
     - .github/workflows/reusable_ci_workflow.yml
     - Directory.Build.props
     - Directory.Build.targets
   tags-ignore:
     - release-*
     - preview-*

  pull_request:
    branches: [ master ]
    paths:
     - src/HealthChecks.Azure.Messaging.ServiceBus/**
     - test/HealthChecks.Azure.Messaging.ServiceBus.Tests/**
     - test/_SHARED/**
     - .github/workflows/healthchecks_azureservicebus_ci.yml
     - .github/workflows/reusable_ci_workflow.yml
     - Directory.Build.props
     - Directory.Build.targets

jobs:
  build:
    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/HealthChecks.Azure.Messaging.ServiceBus/HealthChecks.Azure.Messaging.ServiceBus.csproj
      TEST_PROJECT_PATH: ./test/HealthChecks.Azure.Messaging.ServiceBus.Tests/HealthChecks.Azure.Messaging.ServiceBus.Tests.csproj
      CODECOV_FLAGS: AzureServiceBus

