name: HealthChecks IbmMQ CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.IbmMQ/**
      - test/HealthChecks.IbmMQ.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_ibmmq_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.IbmMQ/**
      - test/HealthChecks.IbmMQ.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_ibmmq_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    services:
      ibmmq:
        image: ibmcom/mq
        ports:
          - 1414:1414
          - 9157:9157
        env:
          LICENSE: accept
          MQ_QMGR_NAME: QM1
          MQ_APP_PASSWORD: 12345678
          MQ_ENABLE_METRICS: true

    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/HealthChecks.IbmMQ/HealthChecks.IbmMQ.csproj
      TEST_PROJECT_PATH: ./test/HealthChecks.IbmMQ.Tests/HealthChecks.IbmMQ.Tests.csproj
      CODECOV_FLAGS: IbmMQ
