name: HealthChecks EventStore CI

on:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.EventStore/**
      - test/HealthChecks.EventStore.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_eventstore_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.EventStore/**
      - test/HealthChecks.EventStore.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_eventstore_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    services:
      eventstore:
        image: eventstore/eventstore
        ports:
          - "2113:2113"
          - "1113:1113"
        env:
          EVENTSTORE_INSECURE: true
          EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: true
          EVENTSTORE_ENABLE_EXTERNAL_TCP: true

    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/HealthChecks.EventStore/HealthChecks.EventStore.csproj
      TEST_PROJECT_PATH: ./test/HealthChecks.EventStore.Tests/HealthChecks.EventStore.Tests.csproj
      CODECOV_FLAGS: EventStore
