name: HealthChecks Nats CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.Nats/**
      - test/HealthChecks.Nats.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_nats_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.Nats/**
      - test/HealthChecks.Nats.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_nats_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    services:
      nats:
        image: nats:latest
        ports:
        - "4222:4222"
        - "8222:8222"
        - "6222:6222"

    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/HealthChecks.Nats/HealthChecks.Nats.csproj
      TEST_PROJECT_PATH: ./test/HealthChecks.Nats.Tests/HealthChecks.Nats.Tests.csproj
      CODECOV_FLAGS: Nats
