name: HealthChecks Azure KeyVault Secrets CD

on:
  push:
    tags:
      - release-azurekeyvault-secrets-*
      - release-all-*
      
jobs:
  build:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.Azure.KeyVault.Secrets/HealthChecks.Azure.KeyVault.Secrets.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Azure.KeyVault.Secrets