name: HealthChecks MongoDb CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.MongoDb/**
      - test/HealthChecks.MongoDb.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_mongodb_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.MongoDb/**
      - test/HealthChecks.MongoDb.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_mongodb_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/HealthChecks.MongoDb/HealthChecks.MongoDb.csproj
      TEST_PROJECT_PATH: ./test/HealthChecks.MongoDb.Tests/HealthChecks.MongoDb.Tests.csproj
      CODECOV_FLAGS: MongoDb
