name: HealthChecks OpenIdConnectServer CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.OpenIdConnectServer/**
      - test/HealthChecks.IdSvr.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_idsvr_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.OpenIdConnectServer/**
      - test/HealthChecks.IdSvr.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_idsvr_ci.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    services:
      idsvr:
        image: nakah/identityserver4
        ports:
          - 8888:80

    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/HealthChecks.OpenIdConnectServer/HealthChecks.OpenIdConnectServer.csproj
      TEST_PROJECT_PATH: ./test/HealthChecks.OpenIdConnectServer.Tests/HealthChecks.OpenIdConnectServer.Tests.csproj
      CODECOV_FLAGS: OpenIdConnectServer
