name: HealthChecks RabbitMQ CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.Rabbitmq/**
      - test/HealthChecks.RabbitMQ.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_rabbitmq_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.Rabbitmq/**
      - test/HealthChecks.RabbitMQ.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_rabbitmq_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    services:
      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672

    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/HealthChecks.Rabbitmq/HealthChecks.Rabbitmq.csproj
      TEST_PROJECT_PATH: ./test/HealthChecks.RabbitMQ.Tests/HealthChecks.RabbitMQ.Tests.csproj
      CODECOV_FLAGS: RabbitMQ
