name: HealthChecks Oracle CI

on:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.Oracle/**
      - test/HealthChecks.Oracle.Tests/**
      - .github/workflows/healthchecks_oracle_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
  pull_request:
    branches: [ master ]
    paths:
    - src/HealthChecks.Oracle/**
    - test/HealthChecks.Oracle.Tests/**
    - .github/workflows/healthchecks_oracle_ci.yml
    - Directory.Build.props
    - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      oracle:
        image: oracleinanutshell/oracle-xe-11g
        ports:
          - 1521:1521
          - 5500:5500
        env:
          ORACLE_ALLOW_REMOTE: true
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.102
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.Oracle/HealthChecks.Oracle.csproj
    - name: Check formatting
      working-directory: ./src/HealthChecks.Oracle
      run: |
        dotnet format --no-restore --verify-no-changes --severity warn || (echo "Run 'dotnet format' to fix issues" && exit 1)
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.Oracle/HealthChecks.Oracle.csproj
    #- name: Test
    #  run: dotnet test ./test/HealthChecks.Oracle.Tests/HealthChecks.Oracle.Tests.csproj
