name: HealthChecks InfluxDB CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.influxdb/**
      - test/HealthChecks.influxdb.Tests/**
      - .github/workflows/healthchecks_influxdb_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
  pull_request:
    branches: [ master ]
    paths:
    - src/HealthChecks.influxdb/**
    - test/HealthChecks.influxdb.Tests/**
    - .github/workflows/healthchecks_influxdb_ci.yml
    - Directory.Build.props
    - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: |
            6.0.x
            7.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.InfluxDB/HealthChecks.InfluxDB.csproj
    - name: Check formatting
      working-directory: ./src/HealthChecks.InfluxDB
      run: |
        dotnet tool install -g dotnet-format --version 6.0.243104 --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json
        dotnet format --no-restore --verify-no-changes --severity warn whitespace || (echo "Run 'dotnet format' to fix whitespace issues" && exit 1)
        dotnet format --no-restore --verify-no-changes --severity warn analyzers || (echo "Run 'dotnet format' to fix analyzers issues" && exit 1)
        dotnet format --no-restore --verify-no-changes --severity warn style || (echo "Run 'dotnet format' to fix style issues" && exit 1)
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.InfluxDB/HealthChecks.InfluxDB.csproj
    - name: Setup InfluxDB
      uses: influxdata/influxdb-action@v3
      with:
        influxdb_version: latest
        influxdb_org: influxdata
        influxdb_user: ci_user
        influxdb_password: password
        influxdb_bucket: dummy
    - name: Test
      run: dotnet test ./test/HealthChecks.InfluxDB.Tests/HealthChecks.InfluxDB.Tests.csproj --verbosity normal
