name: HealthChecks Oracle CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.Oracle/**
      - test/HealthChecks.Oracle.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_oracle_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.Oracle/**
      - test/HealthChecks.Oracle.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_oracle_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    services:
      oracle:
        image: gvenzl/oracle-xe:18-slim
        ports:
          - 1521:1521
        env:
          ORACLE_PASSWORD: oracle

    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/HealthChecks.Oracle/HealthChecks.Oracle.csproj
      TEST_PROJECT_PATH: ./test/HealthChecks.Oracle.Tests/HealthChecks.Oracle.Tests.csproj
      CODECOV_FLAGS: Oracle
