name: HealthChecks MySql CI

on:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.MySql/**
      - test/HealthChecks.MySql.Tests/**
      - .github/workflows/healthchecks_mysql_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
  pull_request:
    branches: [ master ]
    paths:
    - src/HealthChecks.MySql/**
    - test/HealthChecks.MySql.Tests/**
    - .github/workflows/healthchecks_mysql_ci.yml
    - Directory.Build.props
    - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: Password12!
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.102
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.MySql/HealthChecks.MySql.csproj
    - name: Check formatting
      working-directory: ./src/HealthChecks.MySql
      run: |
        dotnet format --no-restore --verify-no-changes --severity warn || (echo "Run 'dotnet format' to fix issues" && exit 1)
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.MySql/HealthChecks.MySql.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.MySql.Tests/HealthChecks.MySql.Tests.csproj --verbosity normal
