name: HealthChecks Redis CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.Redis/**
      - test/HealthChecks.Redis.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_redis_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.Redis/**
      - test/HealthChecks.Redis.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_redis_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/HealthChecks.Redis/HealthChecks.Redis.csproj
      TEST_PROJECT_PATH: ./test/HealthChecks.Redis.Tests/HealthChecks.Redis.Tests.csproj
      CODECOV_FLAGS: Redis
