name: HealthChecks Arango DB CI

on:
  workflow_dispatch:
  push:
   branches: [ master ]
   paths:
     - src/HealthChecks.ArangoDb/**
     - test/HealthChecks.ArangoDb.Tests/**
     - test/_SHARED/**
     - .github/workflows/healthchecks_arangodb_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
     - Directory.Build.props
     - Directory.Build.targets
   tags-ignore:
     - release-*
     - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.ArangoDb/**
      - test/HealthChecks.ArangoDb.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_arangodb_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    services:
      arangodb:
        image: arangodb/arangodb:latest
        ports:
          - 8529:8529
        env:
          ARANGO_ROOT_PASSWORD: strongArangoDbPassword

    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/HealthChecks.ArangoDb/HealthChecks.ArangoDb.csproj
      TEST_PROJECT_PATH: ./test/HealthChecks.ArangoDb.Tests/HealthChecks.ArangoDb.Tests.csproj
      CODECOV_FLAGS: ArangoDb
