name: HealthChecks System CI

on:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.System/**
      - test/HealthChecks.System.Tests/**
      - .github/workflows/healthchecks_system_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
  pull_request:
    branches: [ master ]
    paths:
    - src/HealthChecks.System/**
    - test/HealthChecks.System.Tests/**
    - .github/workflows/healthchecks_system_ci.yml
    - Directory.Build.props
    - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.102
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.System/HealthChecks.System.csproj
    - name: Check formatting
      working-directory: ./src/HealthChecks.System
      run: |
        dotnet format --no-restore --verify-no-changes --severity warn || (echo "Run 'dotnet format' to fix issues" && exit 1)
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.System/HealthChecks.System.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.System.Tests/HealthChecks.System.Tests.csproj --verbosity normal
