name: HealthChecks Kafka CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.Kafka/**
      - test/HealthChecks.Kafka.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_kafka_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.Kafka/**
      - test/HealthChecks.Kafka.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_kafka_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    services:
      zookeeper:
        image: confluent/zookeeper
        ports:
          - 2181:2181
      kafka:
        image: confluent/kafka
        ports:
          - 9092:9092
        env:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_PORT: 9092

    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/HealthChecks.Kafka/HealthChecks.Kafka.csproj
      TEST_PROJECT_PATH: ./test/HealthChecks.Kafka.Tests/HealthChecks.Kafka.Tests.csproj
      CODECOV_FLAGS: Kafka
