name: HealthChecks Gremlin CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.Gremlin/**
      - test/HealthChecks.Gremlin.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_gremlin_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.Gremlin/**
      - test/HealthChecks.Gremlin.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_gremlin_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    services:
      gremlin:
        image: tinkerpop/gremlin-server
        ports:
          - 8182:8182
        env:
          VIRTUAL_HOST: gremlin.docker
          VIRTUAL_PORT: 8182

    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/HealthChecks.Gremlin/HealthChecks.Gremlin.csproj
      TEST_PROJECT_PATH: ./test/HealthChecks.Gremlin.Tests/HealthChecks.Gremlin.Tests.csproj
      CODECOV_FLAGS: Gremlin
