name: HealthChecks SQL Server DB CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.SqlServer/**
      - test/HealthChecks.SqlServer.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_sqlserver_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.SqlServer/**
      - test/HealthChecks.SqlServer.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_sqlserver_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server
        ports:
          - 5433:1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: Password12!

    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/HealthChecks.SqlServer/HealthChecks.SqlServer.csproj
      TEST_PROJECT_PATH: ./test/HealthChecks.SqlServer.Tests/HealthChecks.SqlServer.Tests.csproj
      CODECOV_FLAGS: SqlServer
