name: HealthChecks Elastic Search CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.Elasticsearch/**
      - test/HealthChecks.Elasticsearch.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_elasticsearch_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.Elasticsearch/**
      - test/HealthChecks.Elasticsearch.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_elasticsearch_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        ports:
          - 9300:9300
          - 9201:9200

    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/HealthChecks.Elasticsearch/HealthChecks.Elasticsearch.csproj
      TEST_PROJECT_PATH: ./test/HealthChecks.Elasticsearch.Tests/HealthChecks.Elasticsearch.Tests.csproj
      CODECOV_FLAGS: Elasticsearch
