name: HealthChecks MySql CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.MySql/**
      - test/HealthChecks.MySql.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_mysql_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.MySql/**
      - test/HealthChecks.MySql.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_mysql_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    services:
      mysql:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: Password12!

    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/HealthChecks.MySql/HealthChecks.MySql.csproj
      TEST_PROJECT_PATH: ./test/HealthChecks.MySql.Tests/HealthChecks.MySql.Tests.csproj
      CODECOV_FLAGS: MySql
