name: HealthChecks NPGSQL DB CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.NpgSql/**
      - test/HealthChecks.Npgsql.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_npgsql_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.NpgSql/**
      - test/HealthChecks.Npgsql.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_npgsql_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    services:
      npgsql:
        image: postgres
        ports:
          - 8010:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Password12!

    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/HealthChecks.NpgSql/HealthChecks.NpgSql.csproj
      TEST_PROJECT_PATH: ./test/HealthChecks.Npgsql.Tests/HealthChecks.Npgsql.Tests.csproj
      CODECOV_FLAGS: Npgsql
