name: HealthChecks AzureServiceBus DB CD

on:
  push:
    tags:
      - release-azureservicebus-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.Azure.Messaging.ServiceBus/HealthChecks.Azure.Messaging.ServiceBus.csproj
      PACKAGE_NAME: HealthChecks.Azure.Messaging.ServiceBus