name: HealthChecks Consul CI

on:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.Consul/**
      - test/HealthChecks.Consul.Tests/**
      - .github/workflows/healthchecks_consul_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
  pull_request:
    branches: [ master ]
    paths:
    - src/HealthChecks.Consul/**
    - test/HealthChecks.Consul.Tests/**
    - .github/workflows/healthchecks_consul_ci.yml
    - Directory.Build.props
    - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      consul:
        image: consul:latest
        ports:
          - 8500:8500
          - 8600:8600
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.Consul/HealthChecks.Consul.csproj
    - name: Check formatting
      working-directory: ./src/HealthChecks.Consul
      run: |
        dotnet format --no-restore --verify-no-changes --severity warn || (echo "Run 'dotnet format' to fix issues" && exit 1)
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.Consul/HealthChecks.Consul.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.Consul.Tests/HealthChecks.Consul.Tests.csproj --verbosity normal
